# Generated by Django 5.1.5 on 2026-01-29 00:20

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True, max_length=50, unique=True, verbose_name="Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed", "Fixed Amount"),
                        ],
                        default="percentage",
                        max_length=20,
                        verbose_name="Discount Type",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage (0-100) or fixed amount",
                        max_digits=10,
                        verbose_name="Discount Value",
                    ),
                ),
                (
                    "max_discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum discount for percentage coupons",
                        max_digits=10,
                        null=True,
                        verbose_name="Maximum Discount",
                    ),
                ),
                (
                    "min_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Minimum Order Value",
                    ),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total times this coupon can be used",
                        null=True,
                        verbose_name="Usage Limit",
                    ),
                ),
                (
                    "usage_limit_per_user",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Usage Limit per User"
                    ),
                ),
                (
                    "times_used",
                    models.PositiveIntegerField(default=0, verbose_name="Times Used"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "valid_from",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Valid From"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Valid Until"
                    ),
                ),
                (
                    "first_purchase_only",
                    models.BooleanField(
                        default=False, verbose_name="First Purchase Only"
                    ),
                ),
                (
                    "specific_categories",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to apply to all categories",
                        related_name="coupons",
                        to="products.category",
                    ),
                ),
                (
                    "specific_products",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Leave empty to apply to all products",
                        related_name="coupons",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="coupons.coupon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon Usage",
                "verbose_name_plural": "Coupon Usages",
            },
        ),
    ]
