# Generated by Django 5.1.5 on 2026-01-29 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("mercadopago", "Mercado Pago"),
                            ("pagseguro", "PagSeguro"),
                            ("stripe", "Stripe"),
                        ],
                        max_length=20,
                        verbose_name="Gateway",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("pix", "PIX"),
                            ("boleto", "Boleto"),
                        ],
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Gateway Fee",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Net Amount",
                    ),
                ),
                (
                    "gateway_payment_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=255,
                        verbose_name="Gateway Payment ID",
                    ),
                ),
                (
                    "gateway_status",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Gateway Status"
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Gateway Response"
                    ),
                ),
                (
                    "pix_qr_code",
                    models.TextField(blank=True, verbose_name="PIX QR Code"),
                ),
                (
                    "pix_qr_code_base64",
                    models.TextField(blank=True, verbose_name="PIX QR Code Base64"),
                ),
                (
                    "pix_expiration",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="PIX Expiration"
                    ),
                ),
                (
                    "boleto_barcode",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Boleto Barcode"
                    ),
                ),
                ("boleto_url", models.URLField(blank=True, verbose_name="Boleto URL")),
                (
                    "boleto_expiration",
                    models.DateField(
                        blank=True, null=True, verbose_name="Boleto Expiration"
                    ),
                ),
                (
                    "refund_reason",
                    models.TextField(blank=True, verbose_name="Refund Reason"),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Refunded At"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("authorization", "Authorization"),
                            ("capture", "Capture"),
                            ("refund", "Refund"),
                            ("chargeback", "Chargeback"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("status", models.CharField(max_length=20, verbose_name="Status")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "gateway_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Gateway Transaction ID",
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Gateway Response"
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Transaction",
                "verbose_name_plural": "Payment Transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
