# Generated by Django 5.1.5 on 2026-01-29 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("url", models.URLField(verbose_name="URL")),
                ("secret", models.CharField(max_length=255, verbose_name="Secret")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "events",
                    models.JSONField(
                        default=list,
                        help_text="List of event types to send",
                        verbose_name="Events",
                    ),
                ),
                (
                    "custom_headers",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Custom Headers"
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Endpoint",
                "verbose_name_plural": "Webhook Endpoints",
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(max_length=100, verbose_name="Event Type"),
                ),
                ("payload", models.JSONField(verbose_name="Payload")),
                (
                    "status_code",
                    models.PositiveIntegerField(verbose_name="Status Code"),
                ),
                (
                    "response_body",
                    models.TextField(blank=True, verbose_name="Response"),
                ),
                ("success", models.BooleanField(verbose_name="Success")),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="webhooks.webhookendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Delivery",
                "verbose_name_plural": "Webhook Deliveries",
                "ordering": ["-created_at"],
            },
        ),
    ]
