# Generated by Django 5.1.5 on 2026-01-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store_name",
                    models.CharField(
                        default="My Store", max_length=200, verbose_name="Store Name"
                    ),
                ),
                (
                    "store_description",
                    models.TextField(blank=True, verbose_name="Store Description"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="settings/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="settings/",
                        verbose_name="Favicon",
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(blank=True, max_length=18, verbose_name="CNPJ"),
                ),
                (
                    "razao_social",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Razão Social"
                    ),
                ),
                (
                    "state_registration",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Inscrição Estadual"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=20, verbose_name="Phone"),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "address_street",
                    models.CharField(blank=True, max_length=200, verbose_name="Street"),
                ),
                (
                    "address_number",
                    models.CharField(blank=True, max_length=20, verbose_name="Number"),
                ),
                (
                    "address_complement",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Complement"
                    ),
                ),
                (
                    "address_neighborhood",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Neighborhood"
                    ),
                ),
                (
                    "address_city",
                    models.CharField(blank=True, max_length=100, verbose_name="City"),
                ),
                (
                    "address_state",
                    models.CharField(blank=True, max_length=2, verbose_name="State"),
                ),
                (
                    "address_zipcode",
                    models.CharField(blank=True, max_length=9, verbose_name="ZIP Code"),
                ),
                ("instagram", models.URLField(blank=True, verbose_name="Instagram")),
                ("facebook", models.URLField(blank=True, verbose_name="Facebook")),
                ("twitter", models.URLField(blank=True, verbose_name="Twitter/X")),
                ("youtube", models.URLField(blank=True, verbose_name="YouTube")),
                ("tiktok", models.URLField(blank=True, verbose_name="TikTok")),
                (
                    "terms_of_service",
                    models.TextField(blank=True, verbose_name="Terms of Service"),
                ),
                (
                    "privacy_policy",
                    models.TextField(blank=True, verbose_name="Privacy Policy"),
                ),
                (
                    "return_policy",
                    models.TextField(blank=True, verbose_name="Return Policy"),
                ),
                (
                    "shipping_policy",
                    models.TextField(blank=True, verbose_name="Shipping Policy"),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="Meta Title"
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Meta Description"
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Meta Keywords"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("BRL", "Brazilian Real"),
                            ("USD", "US Dollar"),
                            ("EUR", "Euro"),
                        ],
                        default="BRL",
                        max_length=3,
                        verbose_name="Currency",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="America/Sao_Paulo",
                        max_length=50,
                        verbose_name="Timezone",
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(default=False, verbose_name="Maintenance Mode"),
                ),
                (
                    "allow_guest_checkout",
                    models.BooleanField(
                        default=True, verbose_name="Allow Guest Checkout"
                    ),
                ),
                (
                    "email_from_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Email From Name"
                    ),
                ),
                (
                    "email_from_address",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email From Address"
                    ),
                ),
            ],
            options={
                "verbose_name": "Store Settings",
                "verbose_name_plural": "Store Settings",
            },
        ),
    ]
