# Generated by Django 5.1.5 on 2026-01-29 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "date",
                    models.DateField(db_index=True, unique=True, verbose_name="Date"),
                ),
                (
                    "total_orders",
                    models.PositiveIntegerField(default=0, verbose_name="Total Orders"),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Total Revenue",
                    ),
                ),
                (
                    "total_items",
                    models.PositiveIntegerField(default=0, verbose_name="Total Items"),
                ),
                (
                    "average_order_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Average Order Value",
                    ),
                ),
                (
                    "cancelled_orders",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Cancelled Orders"
                    ),
                ),
                (
                    "refunded_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Refunded Amount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales Summary",
                "verbose_name_plural": "Sales Summaries",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "path",
                    models.CharField(
                        db_index=True, max_length=500, verbose_name="Path"
                    ),
                ),
                (
                    "user_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="User ID"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Session ID"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP Address"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="User Agent"
                    ),
                ),
                ("referrer", models.URLField(blank=True, verbose_name="Referrer")),
            ],
            options={
                "verbose_name": "Page View",
                "verbose_name_plural": "Page Views",
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="analytics_p_created_4c2b45_idx"
                    ),
                    models.Index(
                        fields=["path", "created_at"],
                        name="analytics_p_path_53ae0e_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="User ID"
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="Session ID"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics_views",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product View",
                "verbose_name_plural": "Product Views",
            },
        ),
    ]
